### ISSUE TITLE
Missing gene from Compara loading: SPMTR.04

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-curation#10]
Ortholog:  SJAG_05153  SPMTR.04

**Comment by ValWood** [comment]
I don't understand this one. Seems to have orthologs:
http://japonicusdb.kmr.nz/gene/SJAG_05153

**Comment by ValWood** [comment]
Close if no action required.

**Comment by kimrutherford** [comment]
> Missing gene from Compara loading

Do you mean missing gene name?  That's because it has 1-many orthologs so nothing is transferred.

**Comment by ValWood** [comment]
I don't know- you opened this one? I don't  see a  problem?

**Comment by kimrutherford** [comment]
> I don't know- you opened this one? I don't see a problem?

Good point!  :-)

I shouldn't be commenting on issues 5 minutes after waking up.

Sorry about that.

**Comment by ValWood** [comment]
I think this was because it did not get a compare ortholog, but it got a Rhind one.
