### ISSUE TITLE
Missing japonicus genes from Rhind ortholog loading

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-curation#11]
SJAG_02175
SJAG_05176
SJAG_05251
SJAG_03979
SJAG_01559
SJAG_01208
SJAG_05275
SJAG_01124
SJAG_05238
SJAG_03110
SJAG_05119
SJAG_05324
SJAG_05281
SJAG_05227
SJAG_01108
SJAG_05318
SJAG_05317
SJAG_02188
SJAG_02272
SJAG_02402
SJAG_02112
SJAG_05282
SJAG_05183
SJAG_03207

**Comment by ValWood** [comment]
Right, these are in the Rhind ortholog predictions but are not in the contigs?
DO they have orthologs? If so could you send them to me?
If they don't maybe they were deleted, I will check with Nick. Or @snezhkaoliferenko
may know?

**Comment by kimrutherford** [comment]
Here is the Rhind ortholog file: https://github.com/japonicusdb/japonicus-curation/blob/main/rhind_pombe_orthologs.tsv

```
SJAG_02175      SPCC569.08c
SJAG_05176      SPCC126.02c
SJAG_05251      SPCC1235.02
SJAG_03979      SPBP35G2.14
SJAG_01559      SPBC3B9.04
SJAG_01208      SPBC32F12.11
SJAG_05275      SPBC17D11.03c
SJAG_01124      SPBC1711.06
SJAG_05238      SPBC16C6.02c
SJAG_03110      SPBC13E7.01
SJAG_05119      SPBC1289.17
SJAG_05324      SPBC106.07c
SJAG_05281      SPAC3G9.02
SJAG_05227      SPAC3G6.02
SJAG_01108      SPAC2F7.06c
SJAG_05318      SPAC2F3.13c
SJAG_05317      SPAC2F3.12c
SJAG_02188      SPAC26H5.11
SJAG_02272      SPAC26A3.16
SJAG_02402      SPAC23E2.03c
SJAG_02112      SPAC21E11.06
SJAG_05282      SPAC1F5.11c
SJAG_05183      SPAC18B11.10
SJAG_03207      SPAC17A5.07c
```

**Comment by ValWood** [comment]
I checked  the first 3 and they are present  but with different IDs so I guess these were removed from the genome a good reason?

**Comment by ValWood** [comment]
Unless we hear otherwise  we will assume these were duplicates, and removed from the ortholog table for good reason, so I will close this ticket. We can reopen if  we get any info.

@snezhkaoliferenko
