### ISSUE TITLE
How many GO annotations post filtering before our additional mapping?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#14]
we imported 32352
but how many of these are redundant (i.e how many  post filtering, but before  our own inferences are added.

(not urgent, but I wnt to put this number in the paper)

**Comment by kimrutherford** [comment]
> but before our own inferences are added

Just to check, do you mean the annotation transferred from pombe via orthologs?

So are you after the number of annotations without including those transferred from pombe?

**Comment by ValWood** [comment]
> So are you after the number of annotations without including those transferred from pombe?

That is correct.
If ew presented only the ones imported from  GOA. I have the 'pre filtering number' (although the current number would be better.
I want the post filtering number (and  to see the numbers slimmed). Will probably focus on  the membrane organization  and cytokinesis terms in the slim.  I want to see how the slim changes.

I wonder if we could have this  'handy'  right up to publication so I can easily pick the best terms relevant to japonicus  to demonstrate the improvement (maybe on the old  URL)

**Comment by ValWood** [comment]
>  (maybe on the old URL)
except that would be confusing for people who haven't switched to the proper URL...

**Comment by kimrutherford** [comment]
OK, thanks.  This will only take an hour or two to run so if you'd like we could leave it until the manuscript is nearly ready.

**Comment by ValWood** [comment]
That would be good. I might even show a side-by side slim, or put it in supp. At least having it there will make it easier to decide what to include.

**Comment by kimrutherford** [comment]
If it helps I think I can make the SVG diagram we need quite quickly.  The sample with just the processes below only took a few minutes.  Let me know what we need.  I'm happy to chat on Skype one morning.

![japonicus-quilt-comp-2](https://user-images.githubusercontent.com/90474/131281199-f2ddf872-e60a-44aa-8058-e8cde055a56f.png)

![japonicus-quilt-comp-3](https://user-images.githubusercontent.com/90474/131281209-bfaf0664-45b0-4d1d-a914-95180782584b.png)

**Comment by ValWood** [comment]
This would be brilliant.

I envisaged scaling the 3 views so that they are  a size so that we could place a single key (one block under the other)
at the right hand side. So each histogramn would also need an aspect label.

I think it is fine to pick out a few "expanded terms". I have no preference which ones (the ones above look good), except I think we should always highlight "unknown" because this will "reduce" rather than increase, and we will refer to it in the text.

Sorry for the delayed response,it was bank holiday here yesterday...

**Comment by kimrutherford** [comment]
OK, I'll give that a go.  I hope you had a good break.

> I envisaged scaling the 3 views so that they are a size so that we could place a single key (one block under the other)
at the right hand side. So each histogramn would also need an aspect label.

That should be no problem.

> except I think we should always highlight "unknown" because this will "reduce" rather than increase, and we will refer to it in the text.

That makes sense.

**Comment by kimrutherford** [comment]
Here's my work in progress.  I'm going to do more tidying tomorrow.  Let me know any changes you'd like.  I've never been good a picking fonts so I could do with help with that.  And do we need the word "GO" everywhere?

![quilt-comp-2](https://user-images.githubusercontent.com/90474/131501481-fd57802e-f75a-45cd-a6ec-1c3fa4d0fc4a.png)

**Comment by kimrutherford** [comment]
Here's a slightly different version.  I'm off to bed now.

![quilt-comp-3](https://user-images.githubusercontent.com/90474/131502182-19ccdb20-b7c7-45fd-ad68-12892939f3b5.png)

**Comment by ValWood** [comment]
They both look great. 
- As this image is likely to be a full page width image, I think the 2nd one is slightly better as this will allow the image to be scaled larger in press and make the key more readable./
- I think the colours are all fine,  but maybe scale the 'negative space' of the unknown as paler I see why you used the grey to contrast with the white background, but I think maybe it will be more obviously different from the others if it is paler. Maybe avoid grey for any other term in the graph (note that you can reuse colours in different aspects if  that helps...there are 2 similar looking purples and 2 similar pinks in the. MF graph where you could do this)
- Another trick from Kilchurch et al  is to bold the terms of interest (i.e unknown here) in the key.
-  Should we include a scale? (it would make it clearer that this is the total protein number, and not just scaled coverage, without reading the legend?

**Comment by ValWood** [comment]
>And do we need the word "GO" everywhere?

It doesn't bother me, but is there a neater way to do the labels @mah11 
any suggestions?

**Comment by ValWood** [comment]
We could  (should probably) use "Biological process (P)" "Cellular component (C)" and "Molecular function (F)" but could perhaps then abbreviate in the key?
and. just use GO in the legend?

**Comment by kimrutherford** [comment]
> I think the colours are all fine, but maybe scale the 'negative space' of the unknown as paler I see why you used the grey to contrast with the white background, but I think maybe it will be more obviously different from the others if it is paler.

Is this enough paler?:

![quilt-comp-4-2](https://user-images.githubusercontent.com/90474/131664870-f9549d2f-f197-4504-bd71-15a7a65f0b60.png)

**Comment by kimrutherford** [comment]
In this one I've slightly rearranged the component columns because I think the connecting lines look better.  Thoughts?

![quilt-comp-4-3](https://user-images.githubusercontent.com/90474/131665920-6ec2ce7b-2fca-49a9-9a06-a3eb0db78c96.png)

**Comment by ValWood** [comment]
yes,  these look nice.
did you try the 'unknowns one more shade lighter? if that doesn't work this is fine...I think the unknowns look different enough to stand out.

**Comment by kimrutherford** [comment]
> did you try the 'unknowns one more shade lighter?

Yep.

I tried a few options for the text but none look great.  Here's the current state but it's easy to change:

![quilt-comp-5](https://user-images.githubusercontent.com/90474/131675588-e8a459ec-9ef2-4d41-936f-970663a2d782.png)

**Comment by ValWood** [comment]
Looks good! @snezhkaoliferenko  see how much we improved the GO annotation!

**Comment by snezhkaoliferenko** [comment]
amazeballs!
