### ISSUE TITLE
check the japonicus/Uniprot mapping file

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#15]
check the japonicus/Uniprot mapping file
Is there one yet?

I suspect this will be because there is only a single Uniprot entry
SJAG_00336 | hhf1
SJAG_03542 | hhf2
in this table do not have orthologs in Compara, I'm not sure why - so may need another way to get GO annotation onto these.

Not required for release as we can work around it.

**Comment by kimrutherford** [comment]
> check the japonicus/Uniprot mapping file
> Is there one yet?

It's here:
https://github.com/japonicusdb/japonicus-curation/blob/main/systematic_id_uniprot_mapping.tsv

**Comment by ValWood** [comment]
OK there are quite a few where multiple proteins map to a single UniPROt entry. This is understandable as these have not yet been reviewed.

   2 B6JVQ3
   2 B6JX14
   2 B6JXG0
   2 B6JXX7
   2 B6JYE7
   2 B6K095
   2 B6K0H3
   2 B6K127
   2 B6K1D5
   2 B6K1L6
   2 B6K422
   2 B6K5E4
   2 B6K628
   2 B6K6J1
   3 B6JV95
   3 B6JV96
   3 B6JYH0
   3 B6K0H2
   5 B6JUV6


I guess it will not affect Japon.db?

Unless there are any knock-on effects anywhere (GPAD? or anything else).
@mah11  are there any worries about not having a 1:1 mapping? I made an effort to get 1:1 for pombe  but maybe if this does not affect us we need not push UniProt to split these entries in a hurry.

**Comment by ValWood** [comment]
Now I am curious what all these are...
SJAG_00027	B6JUV6
SJAG_02135	B6JUV6
SJAG_02945	B6JUV6
SJAG_03828	B6JUV6
SJAG_03903	B6JUV6

**Comment by ValWood** [comment]
http://japonicusdb.kmr.nz/gene_subset/interpro:IPR020828
these should really be separate entries.
I will send the list to Uniprot to split, but internally these are resolved.

**Comment by mah11** [comment]
> @mah11 are there any worries about not having a 1:1 mapping?

that really doesn't look like a question for me!

**Comment by ValWood** [comment]
It is in relation to the GPAD, but I guess if there is a problem we will be alerted.
Anyway I will request a split.

**Comment by ValWood** [comment]
Mailed UniProt helpdesk (I hope)

**Comment by ValWood** [comment]
Unioprot started to do 1:1 mapping but then decided not to. So even in the pombe file we. have some merged and some unmerged hisoines. Doesn't seem to affect us so closing.
