### ISSUE TITLE
a new term 

### ISSUE THREAD

**Issue by snezhkaoliferenko** [japonicusdb/japonicus-curation#17]
Could we please get a term 'deficient in quorum sensing'? 
Thank you!

**Comment by ValWood** [comment]
Actually, could you open it  here instead?
https://github.com/pombase/fypo/issues
and I will close this one. I don't appear to be able to migrate tickets between japonicus and pomBase GitHub

it is better if you open as you will then get a notification from Midori when the term is added to FYPO.

**Comment by snezhkaoliferenko** [comment]
Done.
