### ISSUE TITLE
Orthologs to add

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#22]
following from:
https://github.com/japonicusdb/japonicus-config/issues/32#issuecomment-879018983

add to japonicus manual orthologs file.
Then GO annotation will come automatically.

ACTION: ORTHOLOGS TO ADD
- [x] rrpl14b(will be correctly named to rpl14b)  SJAG_02890   SPAC1805.13
- [x] hhf2 SJAG_03542 SPBC8D2.03c SPAC1834.03c SPBC1105.12
- [x] hhf3  SJAG_00303 SPBC8D2.03c SPAC1834.03c SPBC1105.12
- [x] SJAG_02179  SPAC589.05c

Check that GO annotation propagates

**Comment by ValWood** [comment]
need GO annotation

pombe gene losses
SJAG_00673 | bio3 | 7,8-diamino-pelargonic acid aminotransferase (DAPA) | pombe gene loss
SJAG_01739 |   | Dynactin subunit 4 | pombe gene loss
SJAG_00124 |   | NRG1-like trancriptional repressor, zinc finger C2H2-type | pombe gene loss

**Comment by ValWood** [comment]
@kimrutherford Do we have a place to do this yet? I can't remember!
If so where?

**Comment by kimrutherford** [comment]
All the files are here: https://github.com/japonicusdb/japonicus-curation

If the orthologs are for pombe, you probably want to edit: https://github.com/japonicusdb/japonicus-curation/blob/main/manual_pombe_orthologs.tsv

**Comment by ValWood** [comment]
I edit in the editor. I add tabs, but it looks like this:
<img width="492" alt="Screenshot 2021-07-14 at 11 56 27" src="https://user-images.githubusercontent.com/7359272/125611020-747d0678-00c6-4fc9-9eed-565b87e4ca09.png">
Is that OK? It definitely looks like it should only be a single tab?

Also what format for one to many?
I used:
 SJAG_03542 SPBC8D2.03c|SPAC1834.03c|SPBC1105.12
 SJAG_00303 SPBC8D2.03c|SPAC1834.03c|SPBC1105.12

**Comment by kimrutherford** [comment]
> I edit in the editor. I add tabs, but it looks like this:

The new lines have 2 spaces instead of a tab.

> Also what format for one to many?

Currently it only supports one pair per line like:
SJAG_03542 SPBC8D2.03c|SPAC1834.03c|SPBC1105.12
SJAG_03542 SPBC8D2.03c|SPAC1834.03c|SPBC1105.12
SJAG_03542 SPBC8D2.03c|SPAC1834.03c|SPBC1105.12

**Comment by kimrutherford** [comment]
Sorry, make that:
SJAG_03542 SPBC8D2.03c 
SJAG_03542  SPAC1834.03c 
SJAG_03542  SPBC1105.12

**Comment by kimrutherford** [comment]
Let's do command line Git workshop sometime.  Alternatively, GitHub have a desktop Git application you could use: https://desktop.github.com/

**Comment by ValWood** [comment]
> Let's do command line Git workshop sometime. 

Yes please!

**Comment by ValWood** [comment]
I fixed to this format, but I can't prevent the weird formatting.
SJAG_03542 SPBC8D2.03c
SJAG_03542 SPAC1834.03c
SJAG_03542 SPBC1105.12

**Comment by kimrutherford** [comment]
I've fixed the formatting.
