### ISSUE TITLE
GO annotation to  add to supporting GAF

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#23]
need GO annotation in supporting gaf. ISS from SGD

pombe gene losses
SJAG_00673 | bio3 | 7,8-diamino-pelargonic acid aminotransferase (DAPA) | pombe gene loss
SJAG_01739 |   | Dynactin subunit 4 | pombe gene loss
SJAG_00124 |   | NRG1-like trancriptional repressor, zinc finger C2H2-type | pombe gene loss

**Comment by ValWood** [comment]
@kimrutherford  this isn't critical for release but if a  file exists I will start adding.

**Comment by kimrutherford** [comment]
> this isn't critical for release but if a file exists I will start adding.

No problem.  I'll make GAF file for these annotations once I get back next week.

**Comment by kimrutherford** [comment]
>I'll make GAF file for these annotations once I get back next week.

That's done now.  I've added an empty GAF file in the `japonicus-curation` directory called `manual_go_annotation.gaf` and added it to the load script.

Let me know when you add something to it so I can do a new load.

**Comment by ValWood** [comment]
I'm adding these examples to this file. NO usrgency for add commonly used queries (#41) because I can just do the obvious ones which do not get slimmed in the first instance.

Are you expecting GAF 2.0 or 2.1?

**Comment by mah11** [comment]
GAF 2.0 has gone the way of the dodo. For PomBase the pipeline spits out GAF 2.1, and I run a script that munges it into GAF 2.2 for GOC. I think at least some of the external sources that we use for pb have switched to GAF 2.2, without making pb loading grind to a halt.

**Comment by ValWood** [comment]
Yeah I wasn't sure if  2.1 was enforced for input since it will be spit out in 2.2
I committed a 2.0 but I can change to 2.1...

[main d6de175] GO for lineasge specific gene losses
 1 file changed, 9 insertions(+)

**Comment by ValWood** [comment]
I'm looking at this:
http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/
and I don't see any immediate difference? I see the same17 columns?

**Comment by mah11** [comment]
2.1 -> 2.2 didn't add columns; it added a requirement for column 4 to have "stuff" in every row (and changed the file headers).

**Comment by ValWood** [comment]
right if that is the only difference this file will probably be OK because the relationships will be the default....(the less I have to type into the file, the better)

**Comment by kimrutherford** [comment]
> Are you expecting GAF 2.0 or 2.1?

I'm not completely sure but 2.1 makes sense.

There are a few errors in the log file:
 https://curation.pombase.org/japonicus_nightly/latest_build/logs/log.2021-08-17-06-55-07.manual_go_annotation

There was a missing (empty) column.  I've added it so you'll need to do git pull.

**Comment by ValWood** [comment]
I only saw one error:
Taxon is not a number: taxon_id - skipping
so I fixed that and I'll check again tomorrow.

**Comment by kimrutherford** [comment]
I reloaded JaponicusDB and there are now no errors.  But the annotation didn't load either because the assigned_by column was "Japonicus_DB" instead of "JaponicusDB".  I've fixed that and restarted the load.  Hopefully the annotations will be visible in 50-55 minutes.

**Comment by ValWood** [comment]
What a dope ;)

**Comment by kimrutherford** [comment]
All fixed now I think.  For example: https://www.japonicusdb.org/gene/SJAG_02118

**Comment by ValWood** [comment]
I saw those annotations, but they have disappeared again?
Git clash?

**Comment by ValWood** [comment]
I did an update, but I didn't see a merge problem...

**Comment by kimrutherford** [comment]
> I saw those annotations, but they have disappeared again?

Sorry after that!  I did a re-release of the website but used an old dataset by mistake.  It's fixed now and I've update the command line I use for updated the site so it doesn't happen again.

**Comment by ValWood** [comment]
seem to be there...

**Comment by ValWood** [comment]
Maybe this ticket will help for the external GO file
