### ISSUE TITLE
japonicus genes with no initiator methionine

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#24]
I have come across a couple:
SJAG_05267
SJAG_00273
there may be more. I will check in Artemis.
Or is there a log file anywhere with this info? @kimrutherford

**Comment by kimrutherford** [comment]
> Or is there a log file anywhere with this info?

We don't check for that at the moment.

I did a database query and these genes have a protein sequence that doesn't start with a methione:

```
SJAG_06603
SJAG_04339
SJAG_06643
SJAG_01503
SJAG_03808
SJAG_MIT05
SJAG_04007
SJAG_04943
SJAG_05265
SJAG_00273
SJAG_06592
SJAG_04252
SJAG_03335
SJAG_01262
SJAG_02947
SJAG_01163
SJAG_02043
SJAG_01716
SJAG_06614
SJAG_04843
SJAG_05229
SJAG_04914
SJAG_06608
SJAG_05191
SJAG_01111
SJAG_03130
SJAG_06585
SJAG_06586
SJAG_06639
SJAG_05161
SJAG_01738
SJAG_06638
SJAG_01764
SJAG_05267
SJAG_04347
SJAG_03345
SJAG_06618
SJAG_02459
SJAG_06641
SJAG_06636
SJAG_00037
SJAG_01212
```

**Comment by ValWood** [comment]
thanks, added to gene to fix list.
