### ISSUE TITLE
Compara ortholog to over-ride

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#27]
<img width="515" alt="Screenshot 2021-07-21 at 17 34 36" src="https://user-images.githubusercontent.com/7359272/126552309-9f36ed37-61cf-4b27-8dcd-47203350cf56.png">

Compara predicts the wrong  S.cerevisiae orthologs  for atg1801 and atg1803 (these should all be ATG18).
Need to fix and check  in ortholog over-ride file.  This will be the first  automated ortholog over-ridden example.

**Comment by kimrutherford** [comment]
There's no way to override an ortholog at the moment.  Could you remove the ortholog from the Compara TSV file instead?  It's `compara_pombe_orthologs.tsv` in the japonicus-curation directory.

**Comment by ValWood** [comment]
removed:
SJAG_04963      SPAC823.16c
SJAG_01783      SPAC589.07c
SJAG_01783      SPAC589.07c
from compara_pombe_orthologs.tsv

**Comment by ValWood** [comment]
added
SJAG_04963      SPAC823.16c
SJAG_01783      SPAC589.07c

**Comment by ValWood** [comment]
I think this is a different issue.
I have removed the compare orthologs and added to pombase maual. But these otholog calls SJp. to S. p were  correct.  There are 3 independent copies of atg18 in both species a 1:1 ,mapping. Only one copy in S.c. 

In pombase atg18c has  S. cerevisiae HSV2 for some reason instead of ATG18. I will fix that now.

However, I still don't understand how atg1 has atg21  if the orthologs are transferred preferentially from fission yeast -cerevisiae orthologs (in pombase pombe atg1801 has S. cerevisiae atg18 correctly)?

**Comment by ValWood** [comment]
Actually- Pombase is correct.
It's 
atg1801 and atg1802 -> ATG18
atg1803 -> HSV2

**Comment by ValWood** [comment]
No hurry for this!

**Comment by ValWood** [comment]
One possibility, if pombase has a 1:many it is only using one ortholog (I think any without orthologs default to compare to pick up cerevisiae orthologs that are lost from fission yeast, is that correct?)

**Comment by kimrutherford** [comment]
> However, I still don't understand how atg1 has atg21 if the orthologs are transferred preferentially from fission yeast -cerevisiae orthologs (in pombase pombe atg1801 has S. cerevisiae atg18 correctly)?

Sorry, I'm confused.  Could you add the systematic IDs?

I don't understand "transferred preferentially".  Are you talking about the japonicus-cerevisiae orthologs?  They weren't transferred, we just read them from `cerevisiae_orthologs.tsv` which is from Compara.

**Comment by ValWood** [comment]
Right, we can discuss this sometime. Not urgent.

**Comment by ValWood** [comment]
1.delete 

SJAG_01783 ATG21 (YPL100W) from Compara file

2.Q why does PB. have 
pombe/cerevisiae
atg1801 ATG18
atg1802 ATG18
atg1803 HSV2 (YGR223C)
