### ISSUE TITLE
Submit japonicus GO annotations

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#44]
https://twitter.com/news4go/status/1433118166876516357

I guess!

**Comment by mah11** [comment]
Confirmed on pombase call that this means "submit GO annotations *to GOC*".

Therefore, dependency: first decide on the location where I (and later something automated) can put a GAF in v2.2 format. I should be able to suss that out in connection with https://github.com/japonicusdb/japonicus-config/issues/78. (The daily output for both PomBase and JaponicusDB is still GAF v2.1.)

What is the Twitter link for?

**Comment by ValWood** [comment]
This was so I didn't have to type "Since GO have reported  on twitter that we are curating GO annotations for japonicus  I guess we should think about submitting  them  some time soon"...but that didn't work.

**Comment by mah11** [comment]
that's not what the tweet says anyway - it just says "*has* GO annotations", which doesn't specify that we also curate some and filter the automated lot

**Comment by mah11** [comment]
Note to self: file(s) can go in https://www.japonicusdb.org/data/annotations/Gene_ontology/

**Comment by mah11** [comment]
@ValWood, @snezhkaoliferenko
One more dumb question: what should I put as the contact email?

JaponicusDB doesn't have its own helpdesk address (yet), so I could either leave the pombase helpdesk or put Snezhka's. The pombase helpdesk seems safer, at least to start with, and we can change it any time.

**Comment by ValWood** [comment]
Yes the PomBase helpdesk. We can deal with, or forward.

**Comment by snezhkaoliferenko** [comment]
yes that would be great thank you!
________________________________

**Comment by mah11** [comment]
Pull request opened - it's now in GO's go-site repo, and our share of the setup work is done (unless they have questions, which they'll raise on the PR).

https://github.com/geneontology/go-site/pull/1747
