### ISSUE TITLE
add removed name back SJAG_03830 as synonym

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#45]
SJAG_03830 add to SJAG_07006

**Comment by ValWood** [comment]
added in artt as the name come through from PomBAse orthologs

/systematic_id="SJAG_07006"
/synonym="SJAG_03830"

(i.e not in names_and_products.tsv)

**Comment by kimrutherford** [comment]
That worked, so you can find the gene with the synonym using the search box.

**Comment by ValWood** [comment]
Wow, thanks. I did not expect it to work! It was a tricky one because I wanted the product etc to come from PomBase to keep them  in line if future changes. I wasn't sure if a synonym in Artemis would be recognized!
