### ISSUE TITLE
japonicus orthologs and GO data

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#48]
1. japonicus human and
japonicus pombe
both have NONE for all orthologs 
https://www.japonicusdb.org/data/orthologs/

2. Website downloads mention japonicus /cerevisiae but this is not created
https://www.japonicusdb.org/datasets

3. Manually curated ortholog sets for human and S. cerevisiae; also see documentation
add S. pombe
https://www.japonicusdb.org/datasets

4. ~GO slim IDs and links from documentation page gives and error~ moved to #49
https://www.japonicusdb.org/datasets (near bottom)

5. ~Links to GO annotation go to pombe GO annotation (and file name is pombase)~ moved to #49
https://www.japonicusdb.org/downloads/go-annotations

**Comment by kimrutherford** [comment]
Hi Val.

Could you add URLs for the pages that need to be fixed?

**Comment by ValWood** [comment]
done!

**Comment by kimrutherford** [comment]
> Website downloads mention japonicus /cerevisiae but this is not created

I'm confused by this.  They are created but all the orthologs are "NONE" in the files.  I'm fixing that now.

**Comment by ValWood** [comment]
there is a japonicus human file, and a japonicus pombe file, but not a japonicus cerevisiae file (but it is mentioned on the website)

**Comment by kimrutherford** [comment]
> there is a japonicus human file, and a japonicus pombe file, but not a japonicus cerevisiae file (but it is mentioned on the website)

OK, thanks.  I've edited the Markdown file and I'll check the page in the morning:
https://github.com/pombase/website/blob/master/src/docs/datasets/index.md

**Comment by kimrutherford** [comment]
> japonicus human and
> japonicus pombe
> both have NONE for all orthologs

I think I've fixed this.

**Comment by kimrutherford** [comment]
> there is a japonicus human file, and a japonicus pombe file, but not a japonicus cerevisiae file

I totally mis-read that.  I'll add a japonicus-cerevisiae file.

**Comment by kimrutherford** [comment]
> I'll add a japonicus-cerevisiae file.

I've done that and updated the documentation.  The japonicus nightly load has completed so all the ortholog files are in the [correct place](https://www.japonicusdb.org/data/orthologs/).

I think items 1, 2, and 3 are done now.
