### ISSUE TITLE
Missing ortholog?

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-curation#5]
I've been having a look at japonicus genes without transferred names to make sure the code was working.

This is the first one I checked:
http://japonicusdb.kmr.nz/gene/SJAG_01152

Compara doesn't have a pombe ortholog:
https://fungi.ensembl.org/Schizosaccharomyces_japonicus/Gene/Compara_Ortholog?db=core;g=SJAG_01152;r=supercont5.3:1062675-1066769;t=EEB06113

but it looks a lot like:
https://www.pombase.org/gene/SPBC1711.17

Here's the alignment:
[alignment](https://github.com/japonicusdb/japonicus-curation/files/6507838/align.txt)

**Comment by ValWood** [comment]
Oddly I didn't. get this from github (pinging myself). I just saw it when I went to open another ticket...

**Comment by ValWood** [comment]
If that was the case I would expect to see duplicates in the blast  output but it seems to be all 1:1....
odd

**Comment by ValWood** [comment]
this comment should have beenm before the previous, too many windows...

Yes this is the prp16 ortholog. Odd that Panther did not get this one either:

and it is quite similar
PSI-blast
Select seq ref\|XP_002172406.1\| | ATP-dependent RNA helicase Prp16 [Schizosaccharomyces japonicus yFS275] | Schizosaccharomyces japonicus yFS275 | 1431 | 1431 | 99% | 0.0 | 62.41% | 1176 | XP_002172406.1

oddly panther also puts the pombe one in a funny group
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR18934:SF233
that excludes human prp16.

bizarre, I would have though this one was easy. One possibility is that   althogh they have a common ancestor there was a duplication before the divergence of pombe and S. cerevisiae. This might result in  these being on different branches despite being conserved one to one (if the duplicates(paralogs) were lost from both pombe and cerevisiae.  in this case they would not be *true* orthologs. I will see if I can have a look in the PAINT tree at this.

**Comment by kimrutherford** [comment]
> could you send me the list of japonicus genes withough pombe orthologs again?

It's a bit slow but I did it using QuiLT:
  http://japonicusdb.kmr.nz/vis/from/id/ce0cf99f-1d6e-4837-9087-b5e29523376f

I clicked on the bar for no pombe orthologs, then filtered to get:
  http://japonicusdb.kmr.nz/results/from/id/9b1fd158-7372-4e55-af22-2514249639e3
  http://japonicusdb.kmr.nz/vis/from/id/9b1fd158-7372-4e55-af22-2514249639e3

**Comment by ValWood** [comment]
Some are tRNAs, we can just take the tRNA (or any non-coding RNA)  products and/or names from the contig descriptions

**Comment by ValWood** [comment]
Can this one close?
prp16 gets ortholog from RHind ortholog data.
