### ISSUE TITLE
ortholog file related

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#50]
1.  The "orthologs" link in the right hand menu from JaponicusDB goes to PomBase.
https://www.pombase.org/data/orthologs/

The correct link is used  in the body of the downloads page:
https://www.japonicusdb.org/data/orthologs/

2.  The ortholog file is 2 columns. The first column is the S. japonicus systematic ID. The second column should be the fission yeast systematic ID. Currently it is the fission yeast gene name.

**Comment by kimrutherford** [comment]
> The "orthologs" link in the right hand menu from JaponicusDB goes to PomBase.

Which page is that?

> The ortholog file

Which ortholog file, there are a few.

**Comment by ValWood** [comment]
the page was 
https://www.japonicusdb.org/datasets
but I see this is now fixed

ortholog file is
[japonicus-pombe-orthologs.txt.gz](https://www.japonicusdb.org/data/orthologs/japonicus-pombe-orthologs.txt.gz)

**Comment by kimrutherford** [comment]
> ortholog file is [japonicus-pombe-orthologs.txt.gz](https://www.japonicusdb.org/data/orthologs/japonicus-pombe-orthologs.txt.gz)

OK, thanks.  That's fixed for tonight's load.
