### ISSUE TITLE
JaponicusDB links which point to pombase

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#51]
from
https://www.japonicusdb.org/downloads/phenotype-annotations

1. Modifications
(I'm not sure if there is any modification data curated for japonicus yet?)

2. HCPIN  (remove from the menu, we will not provide this for japonicus)

3.
from 
https://www.japonicusdb.org/downloads/names-and-identifiers

Systematic ID to UniProt accession number
[PomBase2UniProt.tsv](https://www.pombase.org/data/names_and_identifiers/PomBase2UniProt.tsv) tab-delimited file with the PomBase systematic identifier for each protein-coding gene mapped to the corresponding UniProt accession number

4. https://www.japonicusdb.org/documents
menu item is empty. Should we just remove this (I am not sure what it is)

**Comment by kimrutherford** [comment]
I think I've removed those things for tonight's load.

**Comment by kimrutherford** [comment]
All fixed now.
