### ISSUE TITLE
New japonicus names wcs1, wcs2

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#52]
@snezhkaoliferenko @kimrutherford 

SJAG_02860 wcs1 
SJAG_05242 wcs2 
Niki in PMID: [23873862](https://pubmed.ncbi.nlm.nih.gov/23873862)

name description "white-collar for Neurospora homologs" (@kimrutherford  I don't think we can add this info for japonicus? is there a way- I do it in contigs for pombe. Maybe wait until we do this outside of Artemis, but I can keep a list)

**Comment by ValWood** [comment]
Also note, if it is useful, a GO process for https://www.ebi.ac.uk/QuickGO/term/GO:0009785 blue light signaling pathway

crazy stuff! blue light, wtf? this would be the first fungal gene annotated to this therm for GO!

<img width="255" alt="Screenshot 2022-11-23 at 20 44 24" src="https://user-images.githubusercontent.com/7359272/203642903-526db100-bb5a-49ce-98b1-870b3712996b.png">

**Comment by ValWood** [comment]
Oh a question, how does
"white-collar for Neurospora homologs" translate to wcs? or doesn't it ?
(I would expect wcn, but maybe it is  
White-Collar for neurospora homologS?

**Comment by ValWood** [comment]
@Antonialock  you might be interested in this:
Many fungi respond to light and regulate fungal development and behavior. A blue light-activated complex has been identified in Neurospora crassa as the product of the wc-1 and wc-2 genes. Orthologs of WC-1 and WC-2 have hitherto been found only in filamentous fungi and not in yeast, with the exception of the basidiomycete pathogenic yeast **Cryptococcus**. Here, we report that the fission yeast Schizosaccharomyces japonicus responds to blue light depending on Wcs1 and Wcs2, orthologs of components of the WC complex. 

and the UniProt annotation 
https://www.uniprot.org/uniprotkb/Q01371/entry
should move down to 
photoreceptor activity-> GO:0009882  blue light photoreceptor activity

**Comment by snezhkaoliferenko** [comment]
hah 😉 well, they called it wcs1/2 in the paper - and i reasoned it was homologS!

yes, the Neurospora WC-1 and WC-2 are reasonably well studied - i looked at a couple papers and there are more. japonicus has them both (the blue light photoreceptor wcs1 and the accompanying transcription factor wcs2) but lacks other proteins responsible for entraining this system into the circadian clock.

thank you!! also, for that GO link.
sx

________________________________

**Comment by ValWood** [comment]
I added them as
#systematic_id  primary_name    synonyms        product
SJAG_02860      wcs1            blue light photoreceptor Wcs1
SJAG_05242      wcs2            blue light signalling transcription factor, zf-GATA type Wcs2

can edit if necessary... should be updated in a couple of days.
you can use SJAG_02860  and everything will update automagically including allele prefixes.


The file is here:
https://github.com/japonicusdb/japonicus-curation/blob/main/names_and_products.tsv
you can probably edit it (with the little pen).
This file has the names, products and synonym that are not derived directly from the pombe orthologs.

**Comment by snezhkaoliferenko** [comment]
ahh thank you! looks great.
like the word "automagically" 😉 reflects the essence

also, understood re: the table!

i even cropped a little thumb image for this paper so we can update the highlights once the annotation is done 😉 it's cute.

thanks again!
sx

________________________________

**Comment by ValWood** [comment]
Right durr, that's how we do name descriptions for pombe, so I can do them the same way. I will do that.

**Comment by ValWood** [comment]
OK I added the name descriptions in Artemis, will check if that worked tomorrow

**Comment by ValWood** [comment]
> like the word "automagically" 😉 reflects the essence

Thats a word I learned. from @mah11 

> i even cropped a little thumb image for this paper so we can update the highlights once the annotation is done 😉 it's cute.

cool.

I also meant to mention, you can use the Systematic_Ids as allele prefixes, and when a 'real' name is added these will be updated (I think)

**Comment by kimrutherford** [comment]
> OK I added the name descriptions in Artemis, will check if that worked tomorrow

Looks OK:
https://www.japonicusdb.org/gene/SJAG_02860
https://www.japonicusdb.org/gene/SJAG_05242
