### ISSUE TITLE
Japonicas slim updates

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#56]
Biological process
obsolete metal ion homeostasis (obsolete GO:0055065)	GO:0055065
->
BP inorganic ion homeostasis GO:0098771

Phenotype
transmembrane transporter activity phenotype	FYPO:0002114
->
abnormal transport	FYPO:0001720

**Comment by kimrutherford** [comment]
That's done and on Monday I'll check that it worked.
