### ISSUE TITLE
missing IBA annotation

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#58]
Hi @kimrutherford 

Here is an example page that should have PAINT annotations
 https://www.japonicusdb.org/gene/SJAG_05173

You can see them here
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=B6JUR5

or https://www.japonicusdb.org/gene/SJAG_00059
SJAG_00059
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=B6JUT2&evidenceCode=ECO:0000318&evidenceCodeUsage=descendants

(I opened a new ticket so we don't bug everyone tagged in the old one).

**Comment by kimrutherford** [comment]
Now I've looked in the load script, I haven't included GO_Central as a source yet.  Probably because there was still discussion going on in the other issue.  I'll add GO_Central tomorrow.

**Comment by kimrutherford** [comment]
I've changed the load script to include the PAINT annotations from the GOA file.  I'll check in the morning.

**Comment by kimrutherford** [comment]
> Here is an example page that should have PAINT annotations
> https://www.japonicusdb.org/gene/SJAG_05173

One of the annotations visible in QuickGO (for GO:0005694 "chromosome") is on that JaponicusDB page now, but the others aren't.  Maybe they are filtered by more specific annotations?  If anything looks wrong, let me know and I'll have a look in the morning.

This page has quite a few PAINT IBA annotations: https://www.japonicusdb.org/gene/SJAG_00059

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=B6JUT4&evidenceCode=ECO:0000318&evidenceCodeUsage=descendants

**Comment by ValWood** [comment]
I think it probably is OK taking into account the filtering.

Note that the PAINT annotations should always have more than one entry in the 'with' field. It will always include a Panther ID, plus at least one supporting species ID. Here I can only ever see a single ID on the IBA


<img width="918" alt="Screenshot 2023-09-19 at 16 11 19" src="https://github.com/japonicusdb/japonicus-curation/assets/7359272/2b0a9ca1-d17e-4313-9df8-39694bc9a6b3">

**Comment by kimrutherford** [comment]
> Note that the PAINT annotations should always have more than one entry in the 'with' field.

Sorry, that was a copy and paste error in the config.  Fixed for tonight's load.

**Comment by kimrutherford** [comment]
> Note that the PAINT annotations should always have more than one entry in the 'with' field.

Fixed!  They have lots now:

![image](https://github.com/japonicusdb/japonicus-curation/assets/90474/d3fb8045-75cd-40d0-9d07-9dbb6c1c366d)
