### ISSUE TITLE
export a file of japonicus names for UniProt

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-curation#59]
Uniprot will add links to JaponicusDB.
Also if we output a file of names, format:
B6K366 SJAG_03048 cdc2
with an evidence tag that has JaponicusDB as the source

I will forward the e-mail for background

(we can't do this for pombe because it is manually curated in UniProt!)

**Comment by ValWood** [comment]
Hi Kim,

Can we chat about this. I forgot I wanted to chat about it!

v

**Comment by kimrutherford** [comment]
Hi Val.

Should we include genes which don't have unique UniProt IDs?

```
O14460   SPAC513.01c / eft201
O14460   SPCP31B10.07 / eft202
P09988   SPAC1834.04 / hht1
P09988   SPBC8D2.04 / hht2
P09322   SPAC1834.03c / hhf1
P09322   SPBC1105.12 / hhf3
P09322   SPBC8D2.03c / hhf2
```

**Comment by ValWood** [comment]
Yes to both.

**Comment by kimrutherford** [comment]
Thanks.  In that case this is implemented for tonight's load.  I'll check the file in the morning.

This will be the URL for japonicus:
https://curation.pombase.org/japonicus_nightly/latest_build/misc/uniprot_id_mapping.tsv

This will be the URL for pombe:
https://curation.pombase.org/dumps/latest_build/misc/uniprot_id_mapping.tsv
